### ISSUE TITLE
Implementing RNN Structure

### ISSUE THREAD

**Issue by SamCurtis111** [AI4Finance-LLC/FinRL#195]
Apologies in advance for naivety... I wanted to know about the possibility of applying recurrent networks over the framework (e.g. using LSTM in training)
If this is possible, where / how would it be implemented?

Thanks in advance for any help

**Comment by XiaoYangLiu-FinRL** [comment]
For example, you can use LSTM to encode data into the state.

**Comment by RajS999** [comment]
I was going to ask same question, but tankfully came across this and [another](https://github.com/AI4Finance-LLC/FinRL-Library/issues/51) discussion.

I know that stable-baselines (v1) supported [`LstmPolicy`](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html) and [`RecurrentActorCriticPolicy`](https://stable-baselines.readthedocs.io/en/master/_modules/stable_baselines/common/policies.html). However, stable-baselines3 does not seem to support either as per [this](https://github.com/DLR-RM/stable-baselines3/issues/319) thread.

Also it seems that implementing LSTM in stable-baseline3 is non trivial according to [this](https://github.com/DLR-RM/stable-baselines3/issues/210) thread.

So I was guessing what option I am left with. 

Can you please give me some article link explaining what you exactly meant by "LSTM to encode data into the state" in your last reply.

Also I know FinRL is built atop stable-baselines3 which targets pytorch, whereas stable-baselines (v1) targets tensorflow. So I was guessing about interoperability of FinRL with stable-baselines (v1) as it has support for `LSTMPolicy` etc. Is it possible? If yes with how much efforts? Ever being tried?

**Comment by XiaoYangLiu-FinRL** [comment]
We previously spent less than 30 minutes to switch from tensorflow stable-baselines (v1) to Pytorch stable-baselines3.  So, it will not take too long for you to switch back.

**Comment by Zero1366166516** [comment]
Hello, I have the same problem. I also want to build an LSTM feature extractor on Sb3 for financial time series data, using mlppolicy strategy network. This feature extractor is an LSTM neural network. After reading the above discussion, I want to ask whether fin-rl now has an LSTM algorithm feature extractor. Thank you for your previous exploration.
