### ISSUE TITLE
cannot import name 'BackTestStats' from 'finrl.trade.backtest'

### ISSUE THREAD

**Issue by 891922758** [AI4Finance-LLC/FinRL#205]
When I run FinRL_ensemble_stock_trading_ICAIF_2020.ipynb, the cell reports import error. I think it may should be "backtest_stats" as in FinRL_portfolio_allocation_NeurIPS_2020.ipynb instead of "BackTestStats"
![Snipaste_2021-04-03_16-24-42](https://user-images.githubusercontent.com/41494634/113472970-1e0ce200-9499-11eb-95a5-59c243ce10dd.png)

![3](https://user-images.githubusercontent.com/41494634/113473070-dc306b80-9499-11eb-8a0d-43cb7a43bf53.png)

**Comment by davidsmandrade** [comment]
any news about this error?

**Comment by rayrui312** [comment]
Sorry for the late reply. We updated the function name in the new version. For example, BackTestStats is replaced by backtest_stats. However, some notebooks are not updated then. They are fixed now. You may check finrl.plot.py for specific updates.
