### ISSUE TITLE
Using trained model to predict future prices.

### ISSUE THREAD

**Issue by Aryagm** [AI4Finance-LLC/FinRL#212]
I have a trained a model on the 'AAPL' stock. I backtested it and was happy with its results. I now want to try to predict future prices. Is there a way to do this using the model that I trained?

**Comment by s-diaco** [comment]
Have a look at .ipynb files in the "notebooks" directory, you'd figure out how to train a model and use the trained model for prediction.

**Comment by XiaoYangLiu-FinRL** [comment]
What you mean by "predict future prices"?  RL may provide buying/selling actions.

**Comment by Aryagm** [comment]
Sorry, I wrongly phrased my question. The correct phrasing: How to make the model generate a buy or sell action for the next day?

**Comment by geek2008** [comment]
the lib just let you make a decision on the current condition!

**Comment by XiaoYangLiu-FinRL** [comment]
In RL, the trading agent output an action at the "current" state, which can taking past information into account (say 10 time slots of the past).  So, "the action for the next day" is the agent's output at the next day.

**Comment by chenliqiang1982** [comment]
@Aryagm Have you got the answer you want?

**Comment by XiaoYangLiu-FinRL** [comment]
@chenliqiang1982  The discussion was quite clear, based on the context.  "RL cannot generate actions for a future time".  We should close this issue since it is kinda users' obligation to know the "very" basics.

**Comment by Aryagm** [comment]
Yes, thank you for your help everyone!
