### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase.

### ISSUE THREAD

**Issue by charlielam0615** [AI4Finance-LLC/FinRL#226]
When running the docker: `./docker/bin/start_notebook.sh`, an error is thrown: "docker: invalid reference format: repository name must be lowercase."

This is because the $PWD contains a space. Quoting the path fixes the problem. i.e.

Before 
`docker run -it --rm -v ${PWD}:/home -p 8887:8888 finrl`

After
`docker run -it --rm -v "${PWD}":/home -p 8887:8888 finrl`

**Comment by rayrui312** [comment]
Thanks for pointing it out. We are using your codes ```docker run -it --rm -v "${PWD}":/home -p 8887:8888 finrl``` in the newest version.
