### ISSUE TITLE
wrong definition of action_space in env/env_stocktrading.py ?

### ISSUE THREAD

**Issue by bayareacoder** [AI4Finance-LLC/FinRL#229]
In file `env/env_stocktrading.py` and also in `env/env_portfolio.py`:
`self.action_space = spaces.Box(low = -1, high = 1,shape = (self.action_space,)) `

how can this recursive definition be correct? Should it not be:
`self.action_space = spaces.Box(low = -1, high = 1,shape = (self.stock_dim,))`
?

In fact, the comment above this line in `env/env_portfolio.py` mentions:
` # action_space normalization and shape is self.stock_dim`

Anyways, I guess these files for defining the environment are obsolete since there is a newer version `StockTradingEnvV2` in `multistock_docker.ipynb` and this one defines the state space correctly as
```
        self.state_space = (
            1 + len(self.assets) + len(self.assets) * len(self.daily_information_cols)
        )
```
, right?

**Comment by rayrui312** [comment]
I think the codes in the file ```env/env_stocktrading.py``` and ```env/env_portfolio.py``` are correct. Before this definition, we have assigned the action space dimension to self.action_space. For example, you can see the corresponding codes in lines 48 and 50 in the file ```env/env_stocktrading.py```. And action_space is one input parameter in the StockTradingEnv. 

![1](https://user-images.githubusercontent.com/61444295/126779737-bd98b742-7b39-43d8-85dd-54525ca6ad77.png)

Of course your suggestion: ```self.action_space = spaces.Box(low = -1, high = 1,shape = (self.stock_dim,))``` is also correct. In  the action settings in the file ```env/env_stocktrading.py``` and ```env/env_portfolio.py```, the dimension of the action space is equal to the stock dimension.

The reason for differentiating stock dimension and action space dimension is that **they are NOT necessarily the same in the general case.**  For example, if you are designing an environment for single stock trading using the DQN algorithm, you may consider setting the stock dimension to 1 and the action space dimension to 3, where action 0 means doing nothing, action 1 means buying 100 shares and action 2 means selling 100 shares. 

Hope this helps.
