### ISSUE TITLE
total_reward never changed

### ISSUE THREAD

**Issue by liuqi8827** [AI4Finance-LLC/FinRL#232]
Thanks for your work.

I am facing a problem of training the project.

I found the **total_reward never changed** when I modified to use DDPG algorithm to train the project.

![image](https://user-images.githubusercontent.com/45791783/119436460-c7ac7900-bd4e-11eb-8c64-38645b15ebb8.png)

Can you give me some suggestions?
Thanks a lot!

**Comment by XiaoYangLiu-FinRL** [comment]
Please try to reproduce existing examples, get some experience first, which may help a lot here.  It seems this may be due to some simple errors, and other may not experience it.

**Comment by liuqi8827** [comment]
@XiaoYangLiu-FinRL 

Thanks for your reply.
I changed the learning rate, it worked.
