### ISSUE TITLE
Various notebooks are not working due to incorrect dependencies

### ISSUE THREAD

**Issue by bayareacoder** [AI4Finance-LLC/FinRL#234]
It seems many notebooks are not working due to either dependent files changed or missing.

In home folder: FinRL_ensemble_stock_trading_ICAIF_2020.ipynb
![Screen Shot 2021-05-25 at 10 32 39 AM](https://user-images.githubusercontent.com/8239955/119542574-9169fc00-bd44-11eb-858c-45a44f7db43f.png)

In notebooks folder: multistock_docker.ipynb
![Screen Shot 2021-05-25 at 10 34 35 AM](https://user-images.githubusercontent.com/8239955/119542818-d2faa700-bd44-11eb-87e2-cdb1d57e9701.png)

Master branch of a repo should always work, and in this case it should be possible to run the notebooks to verify the claimed performance of the papers.

**Comment by XiaoYangLiu-FinRL** [comment]
We are actively developing the projects. Notebooks are easy ones for users. If you are not able to make them run, please wait for our updates which may be a little bit longer.

**Comment by bayareacoder** [comment]
With all respect and pls take this as constructive criticism, but unless the issue I reported is fixed I do not believe you should close the issue. My bug report had several thumbs up from other users so they probably ran into the same issue. 
You should not have a master branch that does not run out of the box. If you do development it should be in another branch. Not having a running master branch lowers the credibility of your project so people won't spend time further.

**Comment by XiaoYangLiu-FinRL** [comment]
If you load them onto Google colab, the blue button at the top, they always run well.  It may take more time to configure on you PC locally.   Message received, and will keep updating and checking. 

We are sharing this project for sharing purposes....

**Comment by bayareacoder** [comment]
I tried to run FinRL_ensemble_stock_trading_ICAIF_2020.ipynb in Colab and it doesn't run.
Also, as can be seen in my OP, the issues reported have nothing to do with files not found. 
The issues are that inside the dependent files names of classes, objects or functions were changed.

**Comment by XiaoYangLiu-FinRL** [comment]
Some of them have been updated.  It seems that colab does not work for subfolders, and any small change need to check again.  Actually, we are required to fix colab jupyter notebooks every month, probably we are not following the best way of maintaining codes.
