### ISSUE TITLE
AttributeError: module 'stable_baselines3.common.logger' has no attribute 'record'

### ISSUE THREAD

**Issue by pavelxx1** [AI4Finance-LLC/FinRL#239]
submit issue
```
`Traceback (most recent call last):

  File "/finrl/env/env_stocktrading.py", line 210, in step
    logger.record("environment/portfolio_value", end_total_asset)
AttributeError: module 'stable_baselines3.common.logger' has no attribute 'record'`
```

**Comment by donglinZheng** [comment]
hello, how to solve this problem. I met the same issue.

**Comment by karljmurphy** [comment]
They made some changes to logging in stable baselines

There is an example of the change in this module  - https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/base_class.py

You need to do something along the lines of the following:

from stable_baselines3.common import utils

self._logger = utils.configure_logger(self.verbose, self.tensorboard_log, tb_log_name, reset_num_timesteps)

**Comment by sam44185** [comment]
Can anyone describe the solution to this in more detail? I am following this tutorial for reference. https://github.com/AI4Finance-LLC/FinRL/blob/master/tutorials/tutorial_multistock_docker.ipynb

@BruceYanghy , @spencerR1992 , @XiaoYangLiu-FinRL

**Comment by kmungantiwar** [comment]
> Can anyone describe the solution to this in more detail? I am following this tutorial for reference. https://github.com/AI4Finance-LLC/FinRL/blob/master/tutorials/tutorial_multistock_docker.ipynb
> 
> Update: I fixed this error but a new one has appeared. Now I get 'StockTradingEnvV2' object has no attribute 'verbose'
> 
> @BruceYanghy , @XiaoYangLiu-FinRL

do this
# replace the current import with
from stable_baselines3.common import utils
# insert below line in the class
self.logger = utils.configure_logger()
# all the other places which has reference to logger should be replaced with self.logger

**Comment by Athe-kunal** [comment]
Is it working for you @kmungantiwar and is it getting saved in the environment folder, I have done the necessary changes that you suggested, plus we need to specify the tensorboard dir and name in configure_logger
        self.logger = utils.configure_logger(tensorboard_log=config.TENSORBOARD_LOG_DIR,tb_log_name="environment")
Still, nothing is getting logged.
