### ISSUE TITLE
what's the meaning of each data in "obs"

### ISSUE THREAD

**Issue by liuqi8827** [AI4Finance-LLC/FinRL#244]
Thanks for your work.

what's the meaning of each data in "obs"

1. Stock Dimension: 30, State Space: 301
2. obs.shape torch.Size([1, 301])
3. obs tensor([[ 6.4771e+05,  4.1552e+00,  2.0231e+01,  3.3909e+01,  2.4897e+01,
          1.3842e+01,  4.1516e+01,  1.7063e+01,  2.0658e+01,  1.2195e+02,
          1.6952e+01,  7.2471e+01,  1.1026e+01,  3.8415e+01,  2.7500e+01,
          1.6138e+01,  4.0781e+01,  4.1176e+01,  1.7510e+01,  1.5732e+01,
          1.1833e+01,  8.9879e+00,  3.6661e+01,  2.4883e+01,  2.9461e+01,
          2.2931e+01,  1.5299e+01,  1.5645e+01,  2.2759e+01,  3.7470e+01,
          4.5089e+01,  4.9600e+02,  3.0500e+02,  4.3800e+02,  4.4900e+02,
          6.9200e+02,  3.4400e+02,  6.6000e+02,  3.5400e+02,  3.9900e+02,
          1.2050e+03,  1.5100e+02,  3.9600e+02,  4.5100e+02,  6.0600e+02,
          2.3000e+02,  9.7200e+02,  2.7300e+02,  2.9000e+02,  5.3900e+02,
          3.0600e+02,  3.0700e+02,  9.4600e+02,  2.3100e+02,  5.9800e+02,
          2.4000e+02,  3.0000e+01,  2.6600e+02,  2.6500e+02,  2.2600e+02,
          7.9100e+02,  8.7061e-02,  6.3188e-01,  1.0226e+00,  3.1910e-01,
          6.0864e-02, -1.8086e-01,  1.1793e+00,  7.1391e-01,  4.5660e+00,
         -3.7470e-01,  6.7421e-01,  2.7106e-02,  5.2222e-01,  7.7723e-01,
          3.4106e-01,  6.0768e-01,  5.0547e-01,  2.6456e-01,  2.2755e-01,
          1.0847e-01,  1.9776e-01,  6.3438e-01,  5.6138e-01, -1.3321e-01,
          7.4122e-01,  3.5755e-01, -2.0006e-01,  2.0652e-01, -1.1218e-01,
          2.3581e-01,  4.1885e+00,  2.3274e+01,  3.5404e+01,  2.9132e+01,
          1.4852e+01,  4.3566e+01,  1.8514e+01,  2.2313e+01,  1.2283e+02,
          2.0282e+01,  7.3639e+01,  1.1442e+01,  3.9661e+01,  2.8788e+01,
          1.6669e+01,  4.1076e+01,  4.3501e+01,  1.7724e+01,  1.5937e+01,
          1.2094e+01,  9.6822e+00,  3.7839e+01,  2.5571e+01,  3.1442e+01,
          2.5311e+01,  1.5668e+01,  1.6609e+01,  2.4005e+01,  3.8475e+01,
          4.6512e+01,  3.6653e+00,  1.8706e+01,  3.1051e+01,  2.4124e+01,
          1.3127e+01,  4.0072e+01,  1.5315e+01,  1.8756e+01,  1.0663e+02,
          1.6687e+01,  6.9613e+01,  1.0390e+01,  3.6862e+01,  2.4334e+01,
          1.4146e+01,  3.5702e+01,  4.0548e+01,  1.5557e+01,  1.4712e+01,
          1.0526e+01,  8.1415e+00,  3.4026e+01,  2.3344e+01,  2.7767e+01,
          1.9808e+01,  1.4638e+01,  1.5333e+01,  2.2102e+01,  3.6626e+01,
          4.3360e+01,  6.3583e+01,  5.5440e+01,  5.8158e+01,  5.1149e+01,
          5.3885e+01,  4.9233e+01,  6.0627e+01,  5.8121e+01,  6.1128e+01,
          4.5348e+01,  5.6397e+01,  5.3691e+01,  5.4308e+01,  5.5615e+01,
          5.9736e+01,  5.6406e+01,  5.3825e+01,  5.4221e+01,  5.6205e+01,
          5.6495e+01,  5.3272e+01,  5.3951e+01,  5.7011e+01,  4.8997e+01,
          5.5941e+01,  5.7468e+01,  4.6373e+01,  5.5657e+01,  4.9007e+01,
          5.0078e+01,  1.7081e+02, -6.2457e+00,  6.1475e+01, -3.7098e+01,
         -1.1630e+01, -4.5824e+01,  6.0350e+01,  5.2066e+01,  1.1062e+02,
         -1.6562e+02,  6.5519e+01, -3.8884e+00,  4.0892e+01,  6.7994e+01,
          1.1611e+02,  1.9197e+02, -2.7556e+01,  1.2141e+02,  7.9681e+01,
          8.1519e+01,  5.0988e+01,  6.2987e+01,  6.1778e+01, -5.9919e+01,
          6.7383e+01,  6.0317e+01, -1.1746e+02, -5.3843e+01, -3.1512e+01,
          4.6367e+01,  3.2443e+01,  1.4946e+01,  2.3649e+01,  1.2424e+01,
          3.1457e+00,  4.8769e+00,  3.0097e+01,  3.2645e+01,  2.4903e+01,
          2.0951e+01,  1.2183e+01,  1.5408e+01,  2.8443e+00,  2.2417e+01,
          4.0425e+01,  3.7615e+01,  6.2226e+00,  1.4205e+01,  1.7961e+01,
          2.5719e+01,  1.3872e+01,  6.6184e+00,  1.5266e+01,  2.3626e+00,
          2.4828e+01,  4.5513e+01,  1.4416e+01,  5.9301e+00,  7.0285e+00,
          7.1104e+00,  3.8810e+00,  2.0101e+01,  3.1815e+01,  2.5556e+01,
          1.3834e+01,  4.1532e+01,  1.5495e+01,  1.9411e+01,  1.1041e+02,
          1.8786e+01,  7.1060e+01,  1.0856e+01,  3.7523e+01,  2.5892e+01,
          1.5243e+01,  3.8432e+01,  4.1238e+01,  1.6338e+01,  1.5204e+01,
          1.1411e+01,  8.6630e+00,  3.5596e+01,  2.3823e+01,  2.9997e+01,
          2.1655e+01,  1.4611e+01,  1.6176e+01,  2.2883e+01,  3.7399e+01,
          4.4295e+01,  3.5462e+00,  1.5913e+01,  2.9176e+01,  2.2938e+01,
          1.3056e+01,  4.1338e+01,  1.2107e+01,  1.7528e+01,  9.9066e+01,
          1.7812e+01,  6.8187e+01,  1.0582e+01,  3.6563e+01,  2.2539e+01,
          1.4978e+01,  3.8219e+01,  3.8269e+01,  1.6591e+01,  1.4378e+01,
          1.0714e+01,  8.4569e+00,  3.4191e+01,  2.2028e+01,  2.9729e+01,
          1.9720e+01,  1.3623e+01,  1.6045e+01,  2.1005e+01,  3.7792e+01,
          4.4192e+01]], device='cuda:0')

4. In my opinion, 301 = 1 + 30 * 10．
Therefor, each stock has ten characteristic numbers as follows:
    open, high, low, close, volume, boll_ub, boll_lb, rsi_30, cci_30, dx_30.
    Is it right?
    However, I saved the data_processed_full.csv. I found that there is no number match the **obs**, which is shown above.

Can you give me some suggestions?

**Comment by rayrui312** [comment]
**Obs**  is the observations received by the agent.  It is named 'state' and set in the environment file.  Basically, we use the data in data_processed_full.csv to **produce** the state. **But the state is NOT necessarily the same as the data in data_processed_full.csv.** We could use data after some mathematical calculations, e.g., the total asset value. So, in fact, your opinion may not be right.

I don't know which environment you are using, so I cannot explain the state settings specifically. I think you can go to the codes for the environment and have a look at the state settings. For example,  in line 325 of finrl/env/env_stocktrading.py, the state is set as:

    def _update_state(self):
        if len(self.df.tic.unique())>1:
            # for multiple stock
            state =  [self.state[0]] + \
                      self.data.close.values.tolist() + \
                      list(self.state[(self.stock_dim+1):(self.stock_dim*2+1)]) + \
                      sum([self.data[tech].values.tolist() for tech in self.tech_indicator_list ], [])

        else:
            # for single stock
            state =  [self.state[0]] + \
                     [self.data.close] + \
                     list(self.state[(self.stock_dim+1):(self.stock_dim*2+1)]) + \
                     sum([[self.data[tech]] for tech in self.tech_indicator_list ], [])
                          
        return state


Hope this helps.
