### ISSUE TITLE
How to add stocks into the env

### ISSUE THREAD

**Issue by HumphreyHao** [AI4Finance-LLC/FinRL#256]
Hi guys,
in the real case we not always start our trading from total money, for example, I have 20 aapl 1000 dollars, now I want to train my model from this case. How can I add my aapl stocks into our env?
I found there is a para called previous state, but I dont know how to use this para, and there is no tutorial about this, can anyone give some help?
Much thanks!

**Comment by Athe-kunal** [comment]
You can multiply the number of shares that you own of AAPL with the starting close price. Also, I think you need to add this value to total initial cash

**Comment by HumphreyHao** [comment]
thanks a lot!

**Comment by hokhay** [comment]
> You can multiply the number of shares that you own of AAPL with the starting close price. Also, I think you need to add this value to total initial cash

Hi Athe, sorry for my ignorance but I still don't get it. How can I input my existing stock into the env? Is it through the para, previous state? If so, how should I do it?
Thanks a lot

**Comment by Athe-kunal** [comment]
Hi Hokay. Sorry I am wrong in my explanation. In the env reset function all our holdings are equated to 0. Hence at the start of the episode, you have zero holdings. Maybe you can change that reset function in env_stocktrading.py file. Like, initially we have a list of holdings [0,0,0...(till #stocks)]. Maybe if you have 2 shares of AAPL initially and AAPL comes at the first position given the alphabetical order, your holdings can be [2,0,0,0....(till #stocks)].

**Comment by hokhay** [comment]
I have figured out how to initiate with existing stock portfolio. I want to share to you guys here in case someone want to know how.

Under `trade.py` add the following code in `env_kwargs`
 ```
"initial": False,
"previous_state": [10000,0,0,0,10,10,10]
```
`initial` is used to inform the program to use previous state information
`previous_state` is array containing the following info.:
`[initial cash, stock price for each stock, amount of stock holding]`
In this particular case, I have 3 stock and my initial cash is 10000, stock prices can arbitrary value and 10 holdings for each stock

Hope this would help others
Jason
