### ISSUE TITLE
Feature Engineering part KeyError

### ISSUE THREAD

**Issue by NurbukeTeker** [AI4Finance-LLC/FinRL#263]
After using DOW_30_TICKER data , I planned to try codes with BIST_30 data.  For DOW 30 data , config.DOW_30_TICKER was enough. For BIST_30 , I was implemented code with ticker names . If I compare BIST_30 and DOW_30 downloaded dataframes, They are exactly same about columns. But in Feature Engineering part, BIST_30 df not worked like DOW_30. And error me that there is keyerror like:

> processed = fe.preprocess_data(df)
------------------------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-79-3a499df0043a> in <module>()
----> 1 processed = fe.preprocess_data(df)

4 frames
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1296             if missing == len(indexer):
   1297                 axis_name = self.obj._get_axis_name(axis)
-> 1298                 raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   1299 
   1300             # We (temporarily) allow for some missing keys with .loc, except in

KeyError: "None of [Index(['tic', 'date', 'macd'], dtype='object')] are in the [columns]"

-----------------------------------------------------------------------------------------------------------

I couldn't figured out why there is key error about these ['tic', 'date', 'macd'] columns. Cause "tic" and "date" are already in df. And "macd" is one of the technical indicator , should come after feature engineering process. 

So I wonder that is there a special function for DOW_30 data behind. Or why this process_data() function didn't work for my data. I also want to share screenshot of two dataframes which are DOW_30 and BIST_30.

DOW_30:

![image](https://user-images.githubusercontent.com/37930894/129001467-4e0295fb-fc22-4f43-b785-201a89f1aa97.png)

BIST_30:

![image](https://user-images.githubusercontent.com/37930894/129001538-ffc33124-bf2b-4d56-90af-6760cde2a00e.png)

Screenshot of error is:

![image](https://user-images.githubusercontent.com/37930894/129001919-de5470be-40f8-4895-8390-7fc14c9cd0d0.png)

**Comment by NurbukeTeker** [comment]
I realized that when historical data has missing values this issue happened. I mean when I printed through source code (data_process()) , I saw the clean_data() function part.  In function df is copied and  pivot tabel created. In creation part if ticker and date not have value in index "Nan" value added to merged_close data frame. In continous part there is dropna() , So my columns fully deleted and can't find the column names for merge part. 
So I mean If there is no missing part in downloaded data but if historically not include  intersection value about date and ticker, in pivot part it automatically adds Nan value. 
I don't want to change source code anymore, so I will change my start time for data download.

**Comment by Waterkin** [comment]
> I realized that when historical data has missing values this issue happened. I mean when I printed through source code (data_process()) , I saw the clean_data() function part. In function df is copied and pivot tabel created. In creation part if ticker and date not have value in index "Nan" value added to merged_close data frame. In continous part there is dropna() , So my columns fully deleted and can't find the column names for merge part.
> So I mean If there is no missing part in downloaded data but if historically not include intersection value about date and ticker, in pivot part it automatically adds Nan value.
> I don't want to change source code anymore, so I will change my start time for data download.

I have exactly the same problem as yours. Changing start time could be an method to solve the problem, but for me, I changed the preprocessing code and replace 'dropna()' with 'fillna(method='bfill').fillna(method='ffill'). After that, it still raise key error and I have no clue because I have already fill the missing values...

**Comment by Athe-kunal** [comment]
You shouldn't use bfill in stock market data, it may lead to data leakage from future to the past.

**Comment by Waterkin** [comment]
> You shouldn't use bfill in stock market data, it may lead to data leakage from future to the past.

ok, thanks for pointing out.
